### ISSUE TITLE
Cannot clone this repo

### ISSUE THREAD

**Issue by Di-Zayn** [theoxo/self-repair#2]
Hello. When I tried to clone this repo, I got this error: 
"This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.",
and the compressed package in the /paper/data cannot be downloaded normally. Can you send me the complete project or the data? Thanks.

**Comment by Di-Zayn** [comment]
Thanks to @qb20nh, I have solved this problem. For anybody who may clone this repo, here is the solution (you can also find it in https://github.com/nabla-c0d3/nassl/issues/17). 
1.Fork the repo to one of your users
2.Go to repo settings
3.Find "Include Git LFS objects in archives" under the Archives section and check it
4.Go to the Danger Zone section, select "Archive this repository"
5.Confirm and authorize.
6.Return to the archived repository.
7.Download as .zip
8.Download will pause for a minute or so before it starts downloading lfs objects. Wait and it should continue.

**Comment by theoxo** [comment]
Thank you for for finding a workaround for this issue!

Uploading the data on github was a mistake; I'll see if I can get github's support help in moving it elsewhere at some point (apparently the only way to reset the data objects is to delete the repository, which I'd rather not do :P)
